#layout: stacked
style: light
layout: sidebar
#style: dark


plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

future: true #show post dated in a future date
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
     - photo-cell
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
    twitter: 240155787
  # unsplash: your_username
  # vk: your_username
    website: https://weileizeng.github.io/
  # youtube: your_username

topics:
  - name: quantum computing report
    web_url: https://quantumcomputingreport.com/
    image_url: https://secureservercdn.net/184.168.47.225/80b.bf1.myftpupload.com/wp-content/uploads/2016/03/Block-Sphere-Large.bmp
  - name: IBM quantum simulator/devices
    web_url: https://quantum-computing.ibm.com/
    image_url: https://quantum-computing.ibm.com/img/intro.c96a9d64.png

  - name: Quantum circuit visualization - qasm2circ
    web_url: https://www.media.mit.edu/quanta/qasm2circ/
    image_url: https://www.media.mit.edu/quanta/qasm2circ/test1.png


  - name: Open-Source Quantum Software Projects
    web_url: https://github.com/qosf/awesome-quantum-software
    image_url: https://raw.githubusercontent.com/qosf/awesome-quantum-software/master/hopf_fibration.png

  - name: SciRate
    web_url: https://scirate.com/
    image_url: https://scirate.com/assets/scirate-logo-white-on-blue-670e4f99529271708e59ae4485cad9bb.png
    
    
people:
  - name: John Preskill
    web_url: http://www.theory.caltech.edu/people/preskill/
    image_url: http://www.theory.caltech.edu/people/preskill/index_files/image002.jpg

  - name: Michael Nielsen
    web_url: http://michaelnielsen.org/
    image_url: http://michaelnielsen.org/images/mn.jpg

  - name: Daniel Gottesman
    web_url: https://www.perimeterinstitute.ca/personal/dgottesman/index.html

  - name: Scott Aaronson
    web_url: https://www.scottaaronson.com/
    image_url: https://www.scottaaronson.com/aarsmall.gif

  - name: Daniel Lidar
    web_url: http://qserver.usc.edu/
    image_url: http://qserver.usc.edu/wordpress/wp-content/uploads/2013/04/Lidar-photo-182x209.jpg

  - name: Kenneth Brown
    web_url: http://brownlab.pratt.duke.edu/
    image_url: https://brownlab.pratt.duke.edu/sites/brownlab.pratt.duke.edu/files/scholars_images/thumb_image_5009222.png

fun:
  - name: Aerial photo by a kite
    web_url: http://sh.sina.com.cn/news/b/2014-05-21/084995625.html
    image_url: http://sh.sinaimg.cn/2014/0521/U10761P18DT20140521084925.jpg

  - name: Flip it!

links:  
  - name: UCR physics
    web_url: https://physics.ucr.edu/colloquia-seminars

  - name: IQIM @CalTech
    web_url: https://www.caltech.edu/campus-life-events/master-calendar/filter?date_start=&date_end=&type=all&search=&past=0&mc=1&series=420
    description: The Institute for Quantum Information and Matter
    
  - name: CMP @CalTech
    web_url: http://www.cmp.caltech.edu/seminars.html
    description: Condensed Matter Physics

  - name: IQI @CaleTech 
    web_url: https://iqim.caltech.edu/iqi-seminars/
    description: Institute for Quantum Information Weekly Seminars

