#layout: stacked
#style: light
layout: sidebar
style: dark


plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
     - photo-cell
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
    website: http://your_website_url
  # youtube: your_username

topics:
  - name: quantum simulator
    web_url: https://quantum-computing.ibm.com/
    image_url: https://quantum-computing.ibm.com/img/intro.c96a9d64.png

  - name: Open QASM
    web_url: https://en.wikipedia.org/wiki/OpenQASM

  - name: qasm2circ
    web_url: https://www.media.mit.edu/quanta/qasm2circ/
    image_url: https://www.media.mit.edu/quanta/qasm2circ/test1.png